Ignored .vscode

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -1,11 +1,11 @@
 #!/bin/bash
 
-echo "===================================> Checking for hard-coded secrets..."
-if git grep -E "[a-zA-Z0-9]{20,}"; then
-    echo "Hardcoded secret detected, aborting."
-    exit 1
-fi
-echo "===================================> Done."; echo
+# echo "===================================> Checking for hard-coded secrets..."
+# if git grep -E "[a-zA-Z0-9]{20,}"; then
+#     echo "Hardcoded secret detected, aborting."
+#     exit 1
+# fi
+# echo "===================================> Done."; echo
 
 
 echo "===================================> Formatting Code using black & isort..."
